import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      // Navigation
      home: 'Home',
      about: 'About',
      services: 'Services',
      menu: 'Menu',
      menu_title: 'Menu',
      contact: 'Contact',
      register: 'Register',
      register_nav: 'Register',
      dashboard: 'Dashboard',
      language: 'Language',
      english: 'English',
      arabic: 'Arabic',
      
      // Hero Section
      hero_title: 'Transform Your Body, Transform Your Life',
      hero_subtitle: 'Elite Training & Nutrition',
      hero_description: 'Saudi Arabia\'s premier strength and fitness platform for athletes seeking peak performance.',
      get_started: 'Get Started',
      get_started_now: 'Get Started Now',
      
      // About Section
      about_evolve: 'About EVOLVE',
      about_hero_description: 'Learn about our mission, vision, and the team behind EVOLVE.',
      about_title: 'Saudi Arabia\'s Leading Strength & Fitness Platform',
      about_p1: 'EVOLVE is Saudi Arabia\'s premier strength and fitness platform designed for athletes looking to perform at their peak. We combine elite training programs, science-backed nutrition, and data-driven performance tracking to help athletes train smarter, recover faster, and compete stronger.',
      about_p2: 'With Saudi Arabia emerging as a global hub for sports and fitness, EVOLVE stands at the forefront - fueling athletic evolution and empowering the next generation of champions.',
      vision_title: 'Our Vision',
      vision_text: 'To lead the transformation of the sports and fitness industry in Saudi Arabia and the Middle East.',
      mission_title: 'Our Mission',
      mission_text: 'A performance-oriented platform that combines strength and fitness training, sports nutrition, and innovative digital tools.',
      our_achievements: 'Our Achievements',
      happy_clients: 'Happy Clients',
      years_experience: 'Years Experience',
      expert_trainers: 'Expert Trainers',
      support: 'Support',
      meet_our_team: 'Meet Our Team',
      team_description: 'Our team of certified fitness professionals and nutrition experts are dedicated to helping you achieve your goals.',
      our_values: 'Our Values',
      excellence: 'Excellence',
      excellence_description: 'We strive for excellence in everything we do, from our training programs to our nutrition plans.',
      integrity: 'Integrity',
      integrity_description: 'We operate with honesty, transparency, and ethical standards in all our interactions.',
      passion: 'Passion',
      passion_description: 'We are passionate about fitness, nutrition, and helping our clients achieve their goals.',
      ready_to_start: 'Ready to Start Your Fitness Journey?',
      cta_description: 'Join EVOLVE today and take the first step towards achieving your fitness and nutrition goals.',
      
      // Services Page
      our_services: 'Our Services',
      services_hero_description: 'Discover our comprehensive range of fitness and nutrition services designed to help you achieve your goals.',
      comprehensive_services: 'Comprehensive Services',
      services_intro: 'We offer a wide range of services tailored to meet your specific fitness and nutrition needs.',
      
      // Service 1 - Elite Training Programs
      service1_title: 'Elite Training Programs',
      service1_description: 'Advanced training programs designed for athletes looking to perform at their peak.',
      service1_item1: 'Personalized Training Plans',
      service1_item2: 'Strength & Conditioning Science',
      service1_item3: 'Progress Tracking & Metrics',
      service1_item4: 'Performance Optimization',
      
      // Service 2 - Performance Nutrition
      service2_title: 'Performance Nutrition',
      service2_description: 'Science-backed nutrition plans to enhance your performance and recovery.',
      service2_item1: 'Customized Meal Plans',
      service2_item2: 'Macro-Specific Diet Protocols',
      service2_item3: 'Sports Nutrition Science',
      service2_item4: 'Supplement Recommendations',
      
      // Service 3 - The EVOLVE App
      service3_title: 'The EVOLVE App',
      service3_description: 'Track your progress, access your plans, and connect with coaches through our mobile app.',
      service3_item1: 'In-App Coaching',
      service3_item2: 'Meal Tracking & Scheduling',
      service3_item3: 'Performance Analytics',
      service3_item4: 'Community Support',
      
      // Service 4 - 1-on-1 Coaching
      service4_title: '1-on-1 Coaching',
      service4_description: 'Personal coaching sessions with our expert trainers.',
      service4_item1: 'Private Training Sessions',
      service4_item2: 'Specialized Guidance',
      service4_item3: 'Personalized Feedback',
      service4_item4: 'Goal-Specific Training',
      
      // Service 5 - Corporate Packages
      service5_title: 'Corporate Packages',
      service5_description: 'Fitness and nutrition solutions for companies and teams.',
      service5_item1: 'Corporate Meal Plans',
      service5_item2: 'Corporate Fitness Programs',
      service5_item3: 'Team Building Activities',
      service5_item4: 'Wellness Workshops',
      
      // Service 6 - Performance Analytics
      service6_title: 'Performance Analytics',
      service6_description: 'Data-driven insights to optimize your training and nutrition.',
      service6_item1: 'Data-Driven Insights',
      service6_item2: 'Progress Tracking',
      service6_item3: 'Performance Optimization',
      service6_item4: 'Customized Reporting',
      
      // Process Section
      our_process: 'Our Process',
      process_description: 'How we work with you to achieve your fitness and nutrition goals.',
      step1_title: 'Consultation',
      step1_description: 'We start with a comprehensive assessment of your current fitness level, goals, and preferences.',
      step2_title: 'Customization',
      step2_description: 'Our experts create personalized plans tailored to your specific needs and goals.',
      step3_title: 'Implementation',
      step3_description: 'You begin your journey with ongoing support and guidance from our team.',
      step4_title: 'Monitoring',
      step4_description: 'We track your progress and make adjustments to ensure optimal results.',
      
      // Pricing Section
      pricing_plans: 'Pricing Plans',
      pricing_description: 'Choose the plan that best fits your needs and budget.',
      basic_plan: 'Basic Plan',
      premium_plan: 'Premium Plan',
      elite_plan: 'Elite Plan',
      most_popular: 'Most Popular',
      choose_plan: 'Choose Plan',
      basic_feature1: 'Access to Basic Training Programs',
      basic_feature2: 'Nutrition Guidelines',
      basic_feature3: 'App Access',
      premium_feature1: 'Personalized Training Program',
      premium_feature2: 'Custom Nutrition Plan',
      premium_feature3: 'Weekly Check-ins',
      premium_feature4: 'Priority Support',
      elite_feature1: '1-on-1 Training Sessions',
      elite_feature2: 'Advanced Performance Analytics',
      elite_feature3: 'Daily Support',
      elite_feature4: 'Access to Exclusive Content',
      elite_feature5: 'Quarterly Assessments',
      
      // CTA Section
      cta_title: 'Transform Your Fitness Journey Today',
      cta_text: 'Join EVOLVE and experience the difference our personalized approach can make.',
      ready_to_transform: 'Ready to Transform Your Fitness Journey?',
      transform_description: 'Join EVOLVE today and take the first step towards achieving your fitness and nutrition goals.',
      
      // Contact Section
      contact_us: 'Contact Us',
      contact_hero_description: 'Get in touch with our team for any inquiries or to schedule a consultation.',
      get_in_touch: 'Get in Touch',
      contact_intro: 'Have questions or ready to start your fitness journey? Reach out to us using any of the methods below.',
      address: 'Address',
      address_text: 'King Fahd Road, Riyadh, Saudi Arabia',
      phone: 'Phone',
      email: 'Email',
      send_message: 'Send Message',
      name: 'Name',
      enter_full_name: 'Enter your full name',
      enter_email: 'Enter your email address',
      enter_phone: 'Enter your phone number',
      message: 'Message',
      enter_message: 'Enter your message',
      sending: 'Sending...',
      message_sent: 'Message Sent!',
      message_error: 'Error sending message. Please try again.',
      follow_us: 'Follow Us',
      
      // FAQ Section
      faq_title: 'Frequently Asked Questions',
      faq_description: 'Find answers to common questions about our services and programs.',
      faq1_question: 'How do I get started with EVOLVE?',
      faq1_answer: 'You can get started by registering on our website or contacting us directly. We\'ll schedule an initial consultation to assess your goals and create a personalized plan.',
      faq2_question: 'Do you offer remote coaching?',
      faq2_answer: 'Yes, we offer remote coaching through our mobile app and online platform. You can access your training programs, nutrition plans, and connect with your coach from anywhere.',
      faq3_question: 'How often will my program be updated?',
      faq3_answer: 'Your program will be updated based on your progress and goals. Typically, we review and adjust programs every 4-6 weeks or as needed.',
      faq4_question: 'Can I switch between plans?',
      faq4_answer: 'Yes, you can upgrade or change your plan at any time. Contact your coach or our support team to discuss your options.',
      
      // Footer
      quick_links: 'Quick Links',
      legal: 'Legal',
      privacy_policy: 'Privacy Policy',
      terms: 'Terms of Service',
      disclaimer: 'Disclaimer',
      hours: 'Hours of Operation',
      mon_fri: 'Monday - Friday: 8am - 8pm',
      saturday: 'Saturday: 9am - 6pm',
      sunday: 'Sunday: 10am - 4pm',
      copyright: '© 2023 EVOLVE. All rights reserved.',
      footer_desc: 'Transforming lives through personalized nutrition and fitness.',
      back_to_top: 'Back to Top',
      
      // Registration Form
      join_evolve: 'Join EVOLVE',
      registration_description: 'Complete the registration to start your fitness journey',
      registration_title: 'انضم إلى إيفولف',
      registration_subtitle: 'أكمل تسجيلك للبدء',
      registration_description: 'أكمل التسجيل لبدء رحلة لياقتك البدنية',
      personal_information: 'المعلومات الشخصية',
      personal_info: 'Personal Information',
      health_goals: 'Health Goals',
      lifestyle_habits: 'Lifestyle & Habits',
      preferences_support: 'Preferences & Support',
      first_name: 'First Name',
      last_name: 'Last Name',
      date_of_birth: 'Date of Birth',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      primary_goal: 'Primary Goal',
      weight_loss: 'Weight Loss',
      muscle_gain: 'Muscle Gain',
      athletic_performance: 'Athletic Performance',
      general_fitness: 'General Fitness',
      current_weight: 'Current Weight',
      target_weight: 'Target Weight',
      height: 'Height',
      activity_level: 'Activity Level',
      sedentary: 'Sedentary',
      lightly_active: 'Lightly Active',
      moderately_active: 'Moderately Active',
      very_active: 'Very Active',
      extremely_active: 'Extremely Active',
      workout_frequency: 'Workout Frequency',
      preferred_workout_time: 'Preferred Workout Time',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      sleep_hours: 'Sleep Hours',
      stress_level: 'Stress Level',
      low: 'Low',
      moderate: 'Moderate',
      high: 'High',
      smoking_status: 'Smoking Status',
      non_smoker: 'Non-Smoker',
      occasional: 'Occasional',
      regular: 'Regular',
      dietary_restrictions: 'Dietary Restrictions',
      vegetarian: 'Vegetarian',
      vegan: 'Vegan',
      gluten_free: 'Gluten Free',
      dairy_free: 'Dairy Free',
      keto: 'Keto',
      paleo: 'Paleo',
      food_allergies: 'Food Allergies',
      supplement_preferences: 'Supplement Preferences',
      communication_preference: 'Communication Preference',
      email_preference: 'Email',
      phone_preference: 'Phone',
      both: 'Both',
      emergency_contact: 'Emergency Contact Name',
      emergency_phone: 'Emergency Contact Phone',
      previous: 'Previous',
      next: 'Next',
      complete_registration: 'Complete Registration',
      enter_first_name: 'Enter your first name',
      enter_last_name: 'Enter your last name',
      
      // Form Validation
      first_name_required: 'First name is required',
      last_name_required: 'Last name is required',
      email_required: 'Email is required',
      email_invalid: 'Please enter a valid email',
      phone_required: 'Phone number is required',
      date_of_birth_required: 'Date of birth is required',
      gender_required: 'Gender is required',
      primary_goal_required: 'Primary goal is required',
      current_weight_required: 'Current weight is required',
      height_required: 'Height is required',
      activity_level_required: 'Activity level is required',
      workout_frequency_required: 'Workout frequency is required',
      workout_time_required: 'Preferred workout time is required',
      sleep_hours_required: 'Sleep hours are required',
      stress_level_required: 'Stress level is required',
      communication_preference_required: 'Communication preference is required',
      emergency_contact_required: 'Emergency contact name is required',
      emergency_phone_required: 'Emergency contact phone is required',
      registering: 'Registering...',
      registration_success: 'Registration Successful!',
      registration_success_message: 'Thank you for registering with EVOLVE. We will contact you shortly to begin your fitness journey.',
      registration_error: 'An error occurred while processing your registration. Please try again.',
      
      // Dashboard
      dashboard_title: 'Your Dashboard',
      dashboard_description: 'Track your progress, access your plans, and manage your account.',
      my_meals: 'My Meals',
      my_workouts: 'My Workouts',
      my_progress: 'My Progress',
      my_account: 'My Account',
      search_meals: 'Search meals...',
      all_categories: 'All Categories',
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
      snacks: 'Snacks',
      add_meal: 'Add Meal',
      edit_meal: 'تعديل الوجبة',
      delete_meal: 'Delete Meal',
      meal_name: 'Meal Name',
      meal_description: 'Meal Description',
      meal_category: 'Meal Category',
      meal_calories: 'Calories',
      meal_protein: 'Protein (g)',
      meal_carbs: 'Carbs (g)',
      meal_fat: 'Fat (g)',
      meal_image: 'Meal Image',
      save_meal: 'Save Meal',
      cancel: 'Cancel',
      confirm_delete: 'Are you sure you want to delete this meal?',
      yes_delete: 'Yes, Delete',
      no_cancel: 'No, Cancel',
      meal_added: 'Meal added successfully!',
      meal_updated: 'Meal updated successfully!',
      meal_deleted: 'Meal deleted successfully!',
      error_occurred: 'An error occurred. Please try again.',
      
      // Meal Detail
      nutrition_facts: 'Nutrition Facts',
      calories: 'Calories',
      protein: 'Protein',
      carbs: 'Carbohydrates',
      fat: 'Fat',
      ingredients: 'المكونات',
      allergens: 'مسببات الحساسية',
      preparation: 'Preparation',
      order_now: 'Order Now',
      add_to_plan: 'Add to My Plan',
      scan_qr: 'Scan QR Code to Order',
      
      // Misc
      loading: 'Loading...',
      error_loading: 'Error loading data. Please try again.',
      no_results: 'No results found.',
      view_details: 'View Details',
      view_all: 'View All',
      learn_more: 'Learn More',
      read_more: 'Read More',
      save: 'Save',
      update: 'Update',
      delete: 'Delete',
      confirm: 'Confirm',
      success: 'Success!',
      error: 'Error!'
    }
  },
  ar: {
    translation: {
      // Navigation
      home: 'الرئيسية',
      about: 'من نحن',
      services: 'الخدمات',
      menu: 'القائمة',
      contact: 'اتصل بنا',
      register: 'التسجيل',
      dashboard: 'لوحة التحكم',
      language: 'اللغة',
      english: 'الإنجليزية',
      arabic: 'العربية',
      
      // Registration Form
      join_evolve: 'انضم إلى إيفولف',
      registration_description: 'أكمل التسجيل لبدء رحلة لياقتك البدنية',
      
      // Form Sections
      basic_information: 'المعلومات الأساسية',
      goals_motivation: 'الأهداف والدافعية',
      health_medical: 'الصحة والطب',
      current_habits: 'العادات الحالية',
      preferences_support: 'التفضيلات والدعم',
      lifestyle_readiness: 'نمط الحياة والاستعداد',
      
      // Basic Information Fields
      full_name: 'الاسم الكامل',
      age: 'العمر',
      gender: 'الجنس',
      height_cm: 'الطول (سم)',
      weight_kg: 'الوزن (كجم)',
      occupation: 'المهنة',
      city_country: 'المدينة والبلد',
      male: 'ذكر',
      female: 'أنثى',
      
      // Goals & Motivation Fields
      target_weight_kg: 'ما هو وزنك المستهدف؟ (كجم)',
      target_date: 'متى تأمل في تحقيق هذا؟',
      weight_loss_reasons: 'لماذا تريد إنقاص الوزن؟ (اختر كل ما ينطبق)',
      motivation_level: 'ما مدى دافعيتك على مقياس من 1-10؟',
      
      // Weight Loss Reasons
      improve_health: 'تحسين الصحة',
      improve_appearance: 'تحسين المظهر',
      increase_energy: 'زيادة الطاقة',
      boost_confidence: 'تعزيز الثقة',
      prepare_event: 'التحضير لحدث',
      doctor_recommendation: 'توصية الطبيب',
      
      // Health & Medical Fields
      medical_conditions: 'هل لديك أي حالات طبية؟ (اختر كل ما ينطبق)',
      medications_question: 'هل تتناول حالياً أي أدوية؟',
      medications_details: 'يرجى تحديد أدويتك',
      food_allergies_question: 'هل لديك أي حساسية غذائية؟',
      food_allergies_details: 'يرجى تحديد حساسيتك الغذائية',
      doctor_clearance: 'هل لديك موافقة من طبيبك لممارسة الرياضة؟',
      
      // Medical Conditions
      diabetes: 'السكري',
      high_blood_pressure: 'ضغط الدم المرتفع',
      heart_disease: 'أمراض القلب',
      thyroid_issues: 'مشاكل الغدة الدرقية',
      joint_problems: 'مشاكل المفاصل',
      none_medical: 'لا يوجد',
      
      // Current Habits Fields
      meals_per_day: 'كم وجبة تتناول يومياً؟',
      eating_out_frequency: 'كم مرة تأكل خارج المنزل؟',
      sugary_drinks: 'كم مرة تشرب المشروبات السكرية؟',
      water_intake: 'كم كوب ماء تشرب يومياً؟',
      sleep_hours: 'كم ساعة تنام ليلاً؟',
      exercise_frequency: 'كم مرة تمارس الرياضة حالياً؟',
      exercise_types: 'ما أنواع التمارين التي تستمتع بها؟ (اختر كل ما ينطبق)',
      
      // Exercise Types
      cardio: 'تمارين القلب',
      weight_training: 'تدريب الأوزان',
      yoga: 'اليوغا',
      swimming: 'السباحة',
      walking: 'المشي',
      sports: 'الرياضات',
      
      // Frequency Options
      never: 'أبداً',
      rarely: 'نادراً',
      sometimes: 'أحياناً',
      often: 'غالباً',
      daily: 'يومياً',
      
      // Preferences & Support Fields
      meal_plan_preference: 'ما نوع خطة الوجبات التي تفضلها؟',
      training_interest: 'هل أنت مهتم بـ:',
      dietary_restrictions_question: 'هل لديك أي قيود دينية أو غذائية؟',
      dietary_restrictions_details: 'حدد قيودك الغذائية',
      coach_gender_preference: 'هل تفضل مدرباً من جنس معين؟',
      support_level: 'كم من الدعم تريد من مدربك؟',
      
      // Meal Plan Preferences
      balanced_diet: 'نظام غذائي متوازن',
      low_carb: 'قليل الكربوهيدرات',
      mediterranean: 'البحر الأبيض المتوسط',
      intermittent_fasting: 'الصيام المتقطع',
      
      // Training Interests
      personal_training: 'التدريب الشخصي',
      group_training: 'التدريب الجماعي',
      online_training: 'التدريب عبر الإنترنت',
      nutrition_consultation_only: 'استشارة التغذية فقط',
      
      // Coach Preferences
      no_preference: 'لا يوجد تفضيل',
      
      // Support Levels
      daily_checkins: 'متابعة يومية',
      weekly_checkins: 'متابعة أسبوعية',
      monthly: 'شهرياً',
      as_needed: 'عند الحاجة فقط',
      
      // Lifestyle & Readiness Fields
      stress_level_question: 'هل تشعر بالتوتر بانتظام؟',
      smoking_status_question: 'هل تدخن أو تستخدم السجائر الإلكترونية؟',
      alcohol_consumption: 'هل تشرب الكحول؟',
      biggest_challenge: 'ما هو أكبر تحدٍ لك في إنقاص الوزن؟',
      past_successes: 'ما الذي نجح معك في الماضي؟',
      support_system: 'هل لديك نظام دعم (أصدقاء/عائلة)؟',
      
      // Common Options
      yes: 'نعم',
      no: 'لا',
      occasionally: 'أحياناً',
      
      // Form Actions
      submit_registration: 'إرسال التسجيل',
      
      // Placeholders
      enter_full_name: 'أدخل اسمك الكامل',
      enter_age: 'أدخل عمرك',
      enter_height: 'أدخل طولك بالسنتيمتر',
      enter_weight: 'أدخل وزنك بالكيلوغرام',
      enter_occupation: 'أدخل مهنتك',
      enter_city_country: 'الرياض، المملكة العربية السعودية',
      enter_target_weight: 'أدخل الوزن المستهدف',
      specify_medications: 'حدد أدويتك',
      specify_allergies: 'حدد حساسيتك الغذائية',
      specify_restrictions: 'حدد قيودك الغذائية',
      describe_challenge: 'اوصف أكبر تحدٍ لك',
      describe_past_success: 'ما الذي نجح معك من قبل؟',
      
      // Validation Messages
      full_name_required: 'الاسم الكامل مطلوب',
      age_required: 'العمر مطلوب',
      gender_required: 'الجنس مطلوب',
      height_required: 'الطول مطلوب',
      weight_required: 'الوزن مطلوب',
      occupation_required: 'المهنة مطلوبة',
      city_country_required: 'المدينة والبلد مطلوبان',
      target_weight_required: 'الوزن المستهدف مطلوب',
      target_date_required: 'التاريخ المستهدف مطلوب',
      motivation_level_required: 'مستوى الدافعية مطلوب',
      doctor_clearance_required: 'موافقة الطبيب مطلوبة',
      meals_per_day_required: 'عدد الوجبات يومياً مطلوب',
      eating_out_frequency_required: 'تكرار الأكل خارج المنزل مطلوب',
      sugary_drinks_required: 'تكرار المشروبات السكرية مطلوب',
      water_intake_required: 'كميء مطلوبة',
      sleep_hours_required: 'ساعات النوم مطلوبة',
      exercise_frequency_required: 'تكرار التمارين مطلوب',
      meal_plan_preference_required: 'تفضيل خطة الوجبات مطلوب',
      coach_gender_preference_required: 'تفضيل جنس المدرب مطلوب',
      support_level_required: 'مستوى الدعم مطلوب',
      stress_level_required: 'مستوى التوتر مطلوب',
      smoking_status_required: 'حالة التدخين مطلوب',
      alcohol_consumption_required: 'استهلاك الكحول مطلوب',
      biggest_challenge_required: 'أكبر تحدٍ مطلوب',
      support_system_required: 'نظام الدعم مطلوب',
      
      // Success/Error Messages
      registering: 'جاري التسجيل...',
      registration_success: 'تم التسجيل بنجاح!',
      registration_success_message: 'شكراً لتسجيلك مع إيفولف. سنتواصل معك قريباً لبدء رحلة لياقتك البدنية.',
      registration_error: 'حدث خطأ أثناء معالجة تسجيلك. يرجى المحاولة مرة أخرى.',
      
      // Dashboard translations
      admin_dashboard: 'لوحة تحكم المدير',
      dashboard_welcome: 'مرحباً بك في لوحة تحكم المدير',
      view_menu: 'عرض القائمة',
      add_new_meal: 'إضافة وجبة جديدة',
      total_meals: 'إجمالي الوجبات',
      total_users: 'إجمالي المستخدمين',
      total_orders: 'إجمالي الطلبات', 
      revenue: 'الإيرادات',
      from_last_month: 'من الشهر الماضي',
      meals_management: 'إدارة الوجبات',
      search_meals: 'البحث في الوجبات...',
      all_categories: 'جميع الفئات',
      salads: 'السلطات',
      bowls: 'الأطباق',
      proteins: 'البروتينات', 
      desserts: 'الحلويات',
      meal: 'الوجبة',
      category: 'الفئة',
      price: 'السعر',
      calories: 'السعرات الحرارية',
      actions: 'الإجراءات',
      edit: 'تعديل',
      delete: 'حذف',
      print_qr: 'طباعة QR',
      cal: 'سعرة',
      meal_name_en: 'اسم الوجبة (إنجليزي)',
      meal_name_ar: 'اسم الوجبة (عربي)',
      description_en: 'الوصف (إنجليزي)',
      description_ar: 'الوصف (عربي)',
      select_category: 'اختر الفئة',
      protein: 'البروتين',
      carbs: 'الكربوهيدرات',
      fat: 'الدهون',
      image_url: 'رابط الصورة',
      cancel: 'إلغاء',
      add_meal: 'إضافة وجبة',
      confirm_delete_meal: 'هل أنت متأكد من حذف هذه الوجبة؟',
      yes_delete: 'Yes, Delete',
      no_cancel: 'No, Cancel',
      meal_added: 'Meal added successfully!',
      meal_updated: 'Meal updated successfully!',
      meal_deleted: 'Meal deleted successfully!',
      error_occurred: 'An error occurred. Please try again.',
      
      // Meal Detail
      nutrition_facts: 'Nutrition Facts',
      calories: 'Calories',
      protein: 'Protein',
      carbs: 'Carbohydrates',
      fat: 'Fat',
      ingredients: 'Ingredients',
      preparation: 'Preparation',
      order_now: 'Order Now',
      add_to_plan: 'Add to My Plan',
      scan_qr: 'Scan QR Code to Order',
      
      // Misc
      loading: 'Loading...',
      error_loading: 'Error loading data. Please try again.',
      no_results: 'No results found.',
      view_details: 'View Details',
      view_all: 'View All',
      learn_more: 'Learn More',
      read_more: 'Read More',
      save: 'Save',
      update: 'Update',
      delete: 'Delete',
      confirm: 'Confirm',
      success: 'Success!',
      error: 'Error!'
    }
  }
};

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem('language') || 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
});

export default i18n;